package web

import (
	"context"
	"encoding/json/v2"
	"net/url"
	"slices"
	"strconv"
	"time"

	"github.com/elmissouri16/snow-core/pkg/protocol"
)

// MessageImage is metadata only. URL is always generated by the manager, never
// accepted from a worker, provider or saved message.
type MessageImage struct {
	Index    int    `json:"index"`
	MIMEType string `json:"mime_type"`
	URL      string `json:"url"`
}

// RuntimeImageBackend reads through the existing owner; it cannot activate a
// worker. The message identity is a current display row, not a browser RPC ID.
type RuntimeImageBackend interface {
	MessageImage(context.Context, string, string, string, string, int) (protocol.RPCCatalogImage, error)
}

func rasterMIME(mime string) bool {
	return mime == "image/png" || mime == "image/jpeg" || mime == "image/gif" || mime == "image/webp"
}

func messageImages(metadata []protocol.RPCMessageImage) []MessageImage {
	var result []MessageImage
	seen := make(map[int]bool)
	for _, image := range metadata {
		if image.Index < 0 || image.Index > 10000 || seen[image.Index] {
			continue
		}
		seen[image.Index] = true
		result = append(result, MessageImage{Index: image.Index, MIMEType: protocol.MessageImageMIME(image.MIMEType)})
		if len(result) == protocol.RPCMessageImageMaxCount {
			break
		}
	}
	return result
}

func promptImages(text string, content []protocol.ContentBlock) []MessageImage {
	offset := 0
	// Agent.PromptContent prepends RPCRequest.Message to content when it is nonempty.
	if text != "" {
		offset = 1
	}
	var metadata []protocol.RPCMessageImage
	for index, block := range content {
		if block.Type == protocol.BlockImage {
			metadata = append(metadata, protocol.RPCMessageImage{Index: index + offset, MIMEType: block.MIMEType})
		}
	}
	return messageImages(metadata)
}

func displayMessageImages(snapshot RuntimeSnapshot, message RuntimeMessage) []MessageImage {
	images := slices.Clone(message.Images)
	for i := range images {
		images[i].URL = ""
		if !runtimeIdentifier(snapshot.ProjectID) || !runtimeIdentifier(snapshot.InstanceID) || !runtimeIdentifier(snapshot.SessionID) || !runtimeIdentifier(message.ID) || !rasterMIME(images[i].MIMEType) || images[i].Index < 0 || images[i].Index > 10000 {
			continue
		}
		if !runtimeIdentifier(message.SourceID) && !runtimeIdentifier(message.SourceTurnID) {
			continue
		}
		query := url.Values{"instance_id": {snapshot.InstanceID}, "session_id": {snapshot.SessionID}}
		if message.SourceTurnID != "" {
			query.Set("turn_id", message.SourceTurnID)
		}
		images[i].URL = "/projects/" + snapshot.ProjectID + "/runtime/images/" + message.ID + "/" + strconv.Itoa(images[i].Index) + "?" + query.Encode()
	}
	return images
}

func imageRow(snapshot RuntimeSnapshot, id string, index int) (RuntimeMessage, MessageImage, bool) {
	for _, message := range snapshot.Messages {
		if message.ID != id || message.Role != "user" {
			continue
		}
		for _, image := range message.Images {
			if image.Index == index && rasterMIME(image.MIMEType) && (runtimeIdentifier(message.SourceID) || runtimeIdentifier(message.SourceTurnID)) {
				return message, image, true
			}
		}
	}
	return RuntimeMessage{}, MessageImage{}, false
}

func validImageResult(result protocol.RPCCatalogImage, session, message string, index int) bool {
	return result.SessionID == session && runtimeIdentifier(result.MessageID) && (message == "" || result.MessageID == message) && result.Index == index && len(result.Data) > 0 && len(result.Data) <= composerMaxImageBytes && validComposerImage(result.MIMEType, result.Data)
}

func (m *RuntimeManager) MessageImage(ctx context.Context, project, instance, session, message string, index int) (protocol.RPCCatalogImage, error) {
	var result protocol.RPCCatalogImage
	if !runtimeIdentifier(session) || !runtimeIdentifier(message) || index < 0 || index > 10000 {
		return result, ErrRuntimeInvalid
	}
	// Independent nonqueued admission leaves Stop and session controls available.
	r, err := m.runtime(project, instance)
	if err != nil {
		return result, err
	}
	if ctx.Err() != nil || m.revalidate(r, project, instance) != nil {
		return result, ErrRuntimeInvalid
	}
	r.mu.Lock()
	if r.imageReads >= 2 {
		r.mu.Unlock()
		return result, ErrRuntimeBusy
	}
	r.imageReads++
	r.mu.Unlock()
	defer func() { r.mu.Lock(); r.imageReads--; r.mu.Unlock() }()
	if !r.processSessionCurrent(session) || !r.supports("message_image") {
		return result, ErrRuntimeInvalid
	}
	projectIdentity := r.project
	projectIdentity.checkIdentity()
	if !projectIdentity.Available {
		return result, ErrProjectInvalid
	}
	r.mu.Lock()
	row, image, ok := imageRow(r.snapshot, message, index)
	r.mu.Unlock()
	if !ok {
		return result, ErrRuntimeInvalid
	}
	p := protocol.RPCMessageImageParams{SessionID: session, MessageID: row.SourceID, Index: index}
	if p.MessageID == "" {
		p.TurnID = row.SourceTurnID
	}
	encoded, err := json.Marshal(p)
	if err != nil {
		return result, ErrRuntimeInvalid
	}
	readCtx, cancel := context.WithTimeout(ctx, 8*time.Second)
	defer cancel()
	stop := context.AfterFunc(r.ctx, cancel)
	defer stop()
	response, err := r.worker.Client.Call(readCtx, protocol.RPCRequest{Type: "message_image", Params: encoded})
	if err != nil || !response.Success {
		return result, ErrRuntimeUnavailable
	}
	encoded, err = json.Marshal(response.Data)
	if err != nil || len(encoded) > 4<<20 || json.Unmarshal(encoded, &result) != nil {
		return protocol.RPCCatalogImage{}, ErrRuntimeUnavailable
	}
	projectIdentity.checkIdentity()
	r.mu.Lock()
	current, currentImage, currentOK := imageRow(r.snapshot, message, index)
	r.mu.Unlock()
	if !projectIdentity.Available || m.revalidate(r, project, instance) != nil || !r.processSessionCurrent(session) || !currentOK || current.SourceID != row.SourceID || current.SourceTurnID != row.SourceTurnID || currentImage.MIMEType != image.MIMEType || result.MIMEType != image.MIMEType || !validImageResult(result, session, row.SourceID, index) {
		return protocol.RPCCatalogImage{}, ErrRuntimeUnavailable
	}
	return result, nil
}
