// Code generated by scripts/sync_textarea.go from Bubbles v2.2.1; DO NOT EDIT.
// Copyright (c) 2020-2026 Charmbracelet, Inc. MIT license; see LICENSE and UPSTREAM.md.
package textarea

import (
	tea "charm.land/bubbletea/v2"
	"github.com/atotto/clipboard"
)

// deleteSelection deletes the currently selected text, positions the cursor
// at the start of the former selection, and clears the selection state. It
// is a no-op when there is no active selection.
func (m *Model) deleteSelection() {
	if !m.HasSelection() {
		return
	}

	start, end, _ := m.Selection()

	if start.Row == end.Row {
		line := m.value[start.Row]
		endCol := min(end.Col, len(line))
		startCol := min(start.Col, endCol)
		m.value[start.Row] = append(line[:startCol], line[endCol:]...)
		m.row = start.Row
		m.SetCursorColumn(startCol)
	} else {
		headLine := m.value[start.Row]
		tailLine := m.value[end.Row]
		endCol := min(end.Col, len(tailLine))
		startCol := min(start.Col, len(headLine))

		merged := make([]rune, 0, startCol+len(tailLine)-endCol)
		merged = append(merged, headLine[:startCol]...)
		merged = append(merged, tailLine[endCol:]...)

		newValue := make([][]rune, 0, len(m.value)-(end.Row-start.Row))
		newValue = append(newValue, m.value[:start.Row]...)
		newValue = append(newValue, merged)
		newValue = append(newValue, m.value[end.Row+1:]...)
		m.value = newValue

		m.row = start.Row
		m.SetCursorColumn(startCol)
	}

	m.ClearSelection()
}

// DeleteSelection deletes the currently selected text, positions the cursor
// at the start of the former selection, and clears the selection state. It
// is a no-op when there is no active selection.
func (m *Model) DeleteSelection() {
	m.deleteSelection()
}

// CopySelection copies the selected text to the clipboard and returns a
// command that performs the copy. Returns nil if there is no selection.
func (m *Model) CopySelection() tea.Cmd {
	if !m.HasSelection() {
		return nil
	}
	text := m.SelectedText()
	return func() tea.Msg {
		if err := clipboard.WriteAll(text); err != nil {
			return copyErrMsg{err}
		}
		return copyMsg(text)
	}
}

// startKeyboardSelection begins a keyboard-driven selection at the current
// cursor position if one is not already active.
func (m *Model) startKeyboardSelection() {
	if !m.hasSelection {
		m.selAnchor = Position{Row: m.row, Col: m.col}
	}
	m.hasSelection = true
	m.selHead = Position{Row: m.row, Col: m.col}
}

// updateKeyboardSelection updates the selection head to the current cursor
// position after a keyboard movement.
func (m *Model) updateKeyboardSelection() {
	m.selHead = Position{Row: m.row, Col: m.col}
}
