// Code generated by scripts/sync_textarea.go from Bubbles v2.2.1; DO NOT EDIT.
// Copyright (c) 2020-2026 Charmbracelet, Inc. MIT license; see LICENSE and UPSTREAM.md.
package textarea

import (
	tea "charm.land/bubbletea/v2"
	"github.com/charmbracelet/x/ansi"
	"strings"
	"unicode"
)

func newDynamicTextArea(minH, maxH int) Model {
	ta := New()
	ta.Prompt = ""
	ta.ShowLineNumbers = false
	ta.DynamicHeight = true
	ta.MinHeight = minH
	ta.MaxHeight = maxH
	ta.SetWidth(20)
	ta.Focus()
	ta, _ = ta.Update(nil)
	return ta
}

func newTextArea() Model {
	textarea := New()

	textarea.Prompt = "> "
	textarea.Placeholder = "Hello, World!"

	textarea.Focus()

	textarea, _ = textarea.Update(nil)

	return textarea
}

func keyPress(key rune) tea.Msg {
	return tea.KeyPressMsg{Code: key, Text: string(key)}
}

func sendString(m Model, str string) Model {
	for _, k := range []rune(str) {
		m, _ = m.Update(keyPress(k))
	}

	return m
}

func stripString(str string) string {
	s := ansi.Strip(str)
	ss := strings.Split(s, "\n")

	var lines []string
	for _, l := range ss {
		trim := strings.TrimRightFunc(l, unicode.IsSpace)
		if trim != "" {
			lines = append(lines, trim)
		}
	}

	return strings.Join(lines, "\n")
}
