window.testComposerAttachments = async assert => {
  "use strict";
  const {openContext, closeContext, $, tick, wait, posts, latest, visible, draft, chips, clear, upload, paste, drop, textFile, png, image, status, reading, send, accept, update, key} = contextTest;
  assert(window.SnowComposerContext && $("#live-prompt") instanceof HTMLTextAreaElement, "production composer module retains native textarea");
  await openContext();
  assert(["attach", "files", "skills"].every(name => visible($(`[data-composer-${name}]`))), "all explicit context controls are visible through the plus menu");
  await closeContext();
  assert($("[data-composer-file-input]").type === "file" && $("[data-composer-file-input]").multiple, "attachment input is native and accepts multiple files");
  assert(posts().length === 0, "passive load sends no discovery, inspection, activation or prompt POST");
  assert(chips().length === 0 && !visible($("[data-composer-mentions]")), "empty composer has neither context nor an unsolicited picker");
  const before = posts().length;
  const source = "snow context α\nline two\n";
  upload([textFile()]); await wait(() => chips().length === 1 && !reading(), "text attachment");
  assert($("[data-composer-context-items]").textContent.includes("notes.txt"), "text attachment shows its filename");
  assert(posts().length === before, "selecting local text performs no upload or prompt");
  assert($("[data-composer-file-input]").value === "", "file input resets for selecting the same file again");
  chips()[0].click();
  assert(chips().length === 0 && posts().length === before, "removing an attachment is local and immediate");
  paste([image()]); await wait(() => chips().length === 1 && !reading(), "pasted image");
  assert($("[data-composer-context-items]").textContent.includes("pixel.png"), "paste captures a local image");
  drop([textFile()]); await wait(() => chips().length === 2 && !reading(), "dropped text");
  assert(posts().length === before, "paste and drop never automatically upload");
  draft("Explain this exactly + & α"); send(); await wait(() => !!latest("prompt-content"), "rich prompt POST");
  const request = latest("prompt-content"), content = JSON.parse(request.fields.content);
  assert(request.url === "/projects/00000000-0000-4000-8000-000000000002/runtime/prompt-content", "rich prompt targets the exact project action");
  assert(Object.keys(request.fields).sort().join(",") === "content,csrf,instance_id,text", "rich prompt contains only four allowed URL-encoded fields");
  assert(request.fields.csrf === "test-csrf" && request.fields.instance_id === "instance-one", "rich prompt preserves CSRF and instance binding");
  assert(request.fields.text === "Explain this exactly + & α", "URL encoding forwards the exact native draft");
  assert(content.every(block => ["text", "image"].includes(block.type)), "rich prompt contains only protocol text/image blocks");
  assert(content.some(block => block.type === "image" && block.mime_type === "image/png" && block.data === png && Object.keys(block).sort().join(",") === "data,mime_type,type"), "image bytes and MIME forward exactly as a protocol block");
  assert(JSON.stringify(content) === JSON.stringify([{type: "text", text: "Attachment: pixel.png\n[Image]"}, {type: "image", mime_type: "image/png", data: png}, {type: "text", text: "Attachment: notes.txt\n" + source}]), "entire ordered content payload forwards exact text, labels and image bytes");
  assert(posts("prompt").length === 0 && chips().length === 2 && $("#live-send").disabled, "pending rich admission retains context and disables duplicate Send");
  send(); await tick();
  assert(posts("prompt-content").length === 1, "duplicate submission cannot replay pending rich content");
  await accept("prompt-content"); await wait(() => chips().length === 0, "accepted context cleanup");
  assert($("#live-prompt").value === "", "accepted unchanged draft clears");
  assert(posts("prompt-content").length === 1, "fresh idle snapshot never resends accepted attachments");
  draft("legacy + & α"); send(); await wait(() => !!latest("prompt"), "legacy prompt");
  assert(latest("prompt").fields.text === "legacy + & α" && !Object.hasOwn(latest("prompt").fields, "content"), "text-only Send retains legacy prompt route and shape");
  await accept("prompt");

  upload([new File(["%PDF-1.7"], "manual.pdf", {type: "application/pdf"})]); await wait(() => !!$(".composer-context-chip.is-error"), "PDF rejection");
  assert(!!$(".composer-context-chip.is-error") && /unsupported|PDF|text|supported/i.test(status()), "PDF rejected with explicit user feedback");
  await clear();
  upload([new File([new Uint8Array([0, 1, 2, 255])], "binary.dat")]); await tick(100);
  assert(!!$(".composer-context-chip.is-error") && !!status(), "binary data rejected explicitly");
  await clear();
  upload([new File([new Uint8Array([0xc3, 0x28])], "invalid.txt", {type: "text/plain"})]); await tick(100);
  assert(!!$(".composer-context-chip.is-error") && !!status(), "invalid UTF-8 cannot enter a text attachment");
  await clear();
  upload([textFile("large.txt", "x".repeat(64 * 1024))]); await tick(100);
  assert(!!$(".composer-context-chip.is-error") && !!status(), "64KiB raw text plus filename label exceeds the text budget");
  await clear();
  upload([new File([new Uint8Array(2 * 1024 * 1024 + 1)], "large.png", {type: "image/png"})]); await tick(100);
  assert(chips().length === 0 && !!status(), "oversized image rejected before admission");
  await clear();
  upload(Array.from({length: 8}, (_, index) => textFile(`part-${index}.txt`, "small")));
  await wait(() => chips().length === 8 && !reading(), "eight attachments");
  assert(chips().length === 8, "eight local attachments are allowed");
  upload([textFile("ninth.txt")]); await tick(100);
  assert(chips().length === 8 && !!status(), "ninth attachment rejected with an explicit limit error");
  assert(posts("prompt-content").length === 1, "all invalid files and budget errors remain local");
  await clear();
  // The real template exports message action capability; a public user message
  // makes the checks meaningful rather than asserting over an empty NodeList.
  update({messages: [{id: "context-user", role: "user", text: "Earlier prompt", html: "<p>Earlier prompt</p>", truncated: false, can_edit: true}]});
  await tick(150);
  upload([textFile()]); await wait(() => chips().length === 1 && !reading());
  const actions = [...document.querySelectorAll("[data-message-edit],[data-message-reuse]")];
  assert(actions.length > 0 && actions.every(button => button.disabled), "attached context disables historical Edit/Reuse controls");
  const queueEnabled = $("#live-session").dataset.queueNextEnabled === "true";
  update({status: "running", queue: {token: "context-queue", revision: 1, can_enqueue: true, items: []}});
  await tick(150);
  const queue = $("[data-queue-next]");
  assert(queueEnabled ? !!queue && queue.disabled : !queue, "attached context disables supported Queue next; legacy capability stays absent");
  const queueRequests = posts("queue-enqueue").length;
  draft("cannot queue attachments"); key("Enter", {ctrlKey: true}); await tick();
  assert(posts("queue-enqueue").length === queueRequests, "Ctrl+Enter cannot bypass the attachment Queue next guard");
  update({status: "idle", queue: null}); await tick(150);
  await clear();
};
