window.testComposerMentions = async assert => {
  "use strict";
  const {openContext, $, tick, wait, posts, latest, visible, draft, nativeInsert, key, chips, clear, status, rows, choose, files, skills, send, accept, swap, reading, update} = contextTest;
  const before = posts().length;
  draft("literal name@example.com"); await tick();
  assert(posts().length === before && !visible($("[data-composer-mentions]")), "embedded at-sign does not browse files");
  draft("Read  afterwards", 5); await nativeInsert("@no");
  await wait(() => !!latest("files"), "native caret-local file query");
  assert(latest("files").url === "/projects/00000000-0000-4000-8000-000000000002/inspect/files" && latest("files").fields.path === "." && latest("files").fields.offset === "0", "caret query requests bounded root directory through inspection route");
  assert(latest("files").fields.csrf === "test-csrf", "file listing remains CSRF-bound");
  latest("files").resolve(files()); await wait(() => rows().length === 1, "filtered file choice");
  assert(rows()[0].textContent.includes("notes.txt") && document.activeElement === $("#live-prompt"), "local name filter preserves native textarea focus");
  const picker = $("[data-composer-mentions]").getBoundingClientRect();
  assert(picker.left >= 0 && picker.right <= innerWidth + 1 && picker.top >= 0 && picker.bottom <= innerHeight && picker.height >= 40, "file popup stays inside viewport with at least a 40px choice area");
  assert(chips().length === 0 && posts("file").length === 0, "single matching filename does not auto-read or attach");
  const listCalls = posts("files").length;
  draft("Read @oth afterwards", 9); await tick();
  assert(rows().length === 1 && rows()[0].textContent.includes("other.txt") && posts("files").length === listCalls, "same-directory typing filters cached names without new requests");
  const home = key("Home"), end = key("End");
  assert(!home.defaultPrevented && !end.defaultPrevented, "Home and End retain textarea editing semantics");
  key("Escape");
  assert(!visible($("[data-composer-mentions]")) && document.activeElement === $("#live-prompt"), "Escape dismisses suggestions without losing draft focus");
  draft("Read @no afterwards", 8); await tick();
  choose("notes.txt"); await wait(() => !!latest("file"), "explicit file read");
  assert(latest("file").url === "/projects/00000000-0000-4000-8000-000000000002/inspect/file" && latest("file").fields.path === "notes.txt", "file selection reads exact inspected project-relative path");
  const text = "full source α\n";
  latest("file").resolve({path: "notes.txt", text, size: new TextEncoder().encode(text).length, truncated: false});
  await wait(() => chips().length === 1 && !reading());
  assert($("#live-prompt").value === 'Read @"notes.txt"  afterwards', "file choice replaces only caret token, preserving surrounding native text");
  assert(posts("prompt-content").length === 1, "inspected file stays local until Send");
  await clear(); draft("@"); await tick();
  const folderTab = key("Tab");
  assert(folderTab.defaultPrevented, "plain Tab accepts the selected folder instead of leaving the composer");
  await wait(() => posts("files").length === listCalls + 1, "directory drill-down");
  assert(latest("files").fields.path === "src" && posts("file").length === 1, "folder choice drills listing without reading a file");
  latest("files").resolve(files("src", [{name: "main.go", path: "src/main.go", kind: "file"}])); await wait(() => rows().length === 1);
  choose("main.go"); await wait(() => posts("file").length === 2);
  latest("file").resolve({path: "src/main.go", text: "partial", size: 70000, truncated: true});
  await wait(() => !!$(".composer-context-chip.is-error"), "truncated file rejection");
  assert(/truncated|partial/i.test(status()) && !$("#live-prompt").value.includes('main.go"'), "truncated preview is explicitly rejected without inserting completed mention");
  const priorSend = posts("prompt-content").length; send(); await tick();
  assert(posts("prompt-content").length === priorSend, "failed file cannot be silently omitted from a rich Send");
  await clear();

  const pagedBefore = posts("files").length;
  draft("@"); await wait(() => posts("files").length === pagedBefore + 1, "unfiltered paged root listing");
  latest("files").resolve({path: ".", entries: [{name: "first.txt", path: "first.txt", kind: "file"}], next_offset: 256, has_more: true, limited: false});
  await wait(() => rows().some(row => row.textContent.includes("More files")), "cached first page with more entries");
  draft("@later");
  await wait(() => posts("files").length === pagedBefore + 2, "automatic bounded cached next-page search");
  assert(latest("files").fields.offset === "256", "nonempty @ filter searches past a cached unmatched page without More files");
  latest("files").resolve(files(".", [{name: "later.txt", path: "later.txt", kind: "file"}]));
  await wait(() => rows().length === 1 && rows()[0].textContent.includes("later.txt"), "later-page exact file suggestion");
  const fileTab = key("Tab");
  assert(fileTab.defaultPrevented, "plain Tab accepts the selected file");
  await wait(() => !!latest("file") && latest("file").fields.path === "later.txt", "Tab-selected file read");
  latest("file").resolve({path: "later.txt", text: "later page", size: 10, truncated: false});
  await wait(() => chips().length === 1 && !reading(), "Tab-selected file attachment");
  await clear();

  await openContext("skills"); await wait(() => !!latest("skills"), "explicit installed skills discovery");
  assert(latest("skills").url === "/projects/00000000-0000-4000-8000-000000000002/runtime/skills" && latest("skills").fields.csrf === "test-csrf" && latest("skills").fields.instance_id === "instance-one", "skill button uses exact CSRF/instance-bound runtime discovery");
  latest("skills").resolve(skills()); await wait(() => rows().length === 3);
  assert($("#live-prompt").value === "$" && posts("prompt").length === 1, "opening skill picker never activates or sends a skill");
  const disabled = rows().find(row => row.textContent.includes("$disabled"));
  assert(disabled?.getAttribute("aria-disabled") === "true" && /Disabled.*configuration/.test(disabled.textContent), "disabled installed skill exposes disabled reason accessibly");
  disabled.click();
  assert($("#live-prompt").value === "$" && visible($("[data-composer-mentions]")), "disabled skill cannot be inserted by clicking");
  draft("$rev"); await wait(() => rows().length === 1);
  assert(rows()[0].textContent.includes("$review") && posts("skills").length === 1, "skill name filtering reuses the explicit discovery response");
  const input = $("#live-prompt"); input.dispatchEvent(new CompositionEvent("compositionstart", {bubbles: true}));
  const imeArrow = key("ArrowDown", {isComposing: true}), imeEnter = key("Enter", {isComposing: true});
  assert(!imeArrow.defaultPrevented && !imeEnter.defaultPrevented && input.value === "$rev", "IME navigation and Enter cannot choose, submit, or prevent composition");
  input.dispatchEvent(new CompositionEvent("compositionend", {bubbles: true})); await wait(() => rows().length === 1);
  assert(input.value === "$rev" && chips().length === 0, "single skill result never auto-inserts or attaches context");
  key("ArrowDown");
  assert(input.getAttribute("aria-activedescendant") === rows()[0].id, "keyboard selection has a valid active-descendant");
  const skillTab = key("Tab");
  assert(skillTab.defaultPrevented && input.value === "$review " && input.selectionStart === input.value.length && !visible($("[data-composer-mentions]")), "plain Tab inserts the exact skill token plus trailing space");
  assert(posts("prompt").length === 1 && posts("prompt-content").length === priorSend, "skill selection never executes automatically");
  send(); await wait(() => posts("prompt").length === 2);
  assert(latest("prompt").fields.text === "$review " && !Object.hasOwn(latest("prompt").fields, "content"), "selected skill activates only through explicit legacy text Send");
  await accept("prompt");
  await swap({instance_id: "instance-disabled"}); draft("$"); await wait(() => posts("skills").length === 2);
  latest("skills").resolve(skills({enabled: false, skills: []})); await wait(() => /Settings → Workspaces/i.test($("[data-composer-mentions]").textContent));
  assert(rows().length === 0 && /Settings → Workspaces/i.test($("[data-composer-mentions]").textContent), "disabled runtime skills direct the user to the saved workspace setting without stale rows");
  key("Enter");
  assert(posts("prompt").length === 2 && $("#live-prompt").value === "$", "unavailable skill picker cannot auto-execute");
  await clear();

  const promptsBeforeCommands = posts("prompt").length;
  draft("/con"); await wait(() => rows().length === 1 && rows()[0].textContent.includes("/context"), "Web command prefix completion");
  assert(rows()[0].querySelector('.composer-mention-icon')?.getAttribute('data-kind') === 'command', "slash suggestions use the command presentation");
  const commandTab = key("Tab");
  await wait(() => $("[data-telemetry-menu]").getAttribute("aria-expanded") === "true", "Tab-selected context command");
  assert(commandTab.defaultPrevented && $("#live-prompt").value === "" && posts("prompt").length === promptsBeforeCommands, "command selection clears its token and never sends a provider prompt");
  key("Escape");

  draft("/login"); await tick();
  assert(rows().length === 0 && /No matching Web Manager commands/.test($("[data-composer-mentions]").textContent), "TUI-only provider login is not advertised in the Web command catalog");
  send(); await tick();
  assert(posts("prompt").length === promptsBeforeCommands && $("#live-prompt").value === "/login", "unsupported slash text is blocked from accidental provider submission while command completion is open");
  draft("/login now"); send(); await tick();
  assert(posts("prompt").length === promptsBeforeCommands && $("#live-prompt").value === "/login now", "argument-bearing unsupported slash text remains command-only instead of becoming a provider prompt");
  draft(""); await tick();

  draft("/plan"); await wait(() => rows().length === 1, "exact Plan command");
  send(); await wait(() => !!latest("mode"), "Send-click Plan command dispatch after prompt blur");
  assert(latest("mode").fields.mode === "plan" && posts("prompt").length === promptsBeforeCommands, "Send-click slash command delegates to the existing typed mode owner, not prompt transport");
  update({mode: "plan"}); latest("mode").resolve(fixture.snapshot); await tick();
  await clear();
};
