export type Project = {
  id: string;
  name: string;
  path: string;
  available: boolean;
  state: string;
  issue: string;
  pinned: boolean;
};

export type Session = {
  id: string;
  name: string;
  updated: string;
  pinned: boolean;
  archived: boolean;
};

export type OrganizationProps = {
  csrf: string;
  error: string;
  organization: null | {
    projects: Project[];
    archived: Project[];
    project: Project | null;
    sessions: Session[];
    offset: number;
    nextURL: string;
    archivedNextURL: string;
    live: boolean;
  };
};

const projectID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const sessionID = /^[A-Za-z0-9_-]{1,128}$/;
const encoder = new TextEncoder();

function record(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function text(value: unknown, bytes: number): value is string {
  return typeof value === 'string' && value.length <= bytes && encoder.encode(value).length <= bytes;
}

function offset(value: unknown): value is number {
  return typeof value === 'number' && Number.isInteger(value) && !Object.is(value, -0) && value >= 0 && value <= 10_000;
}

function project(value: unknown): value is Project {
  if (!record(value) || typeof value.id !== 'string' || !projectID.test(value.id) ||
      !text(value.name, 128) || !value.name || /[\u0000-\u001f\u007f-\u009f]/u.test(value.name) ||
      !text(value.path, 4096) || !value.path.startsWith('/') || value.path.includes('\0') ||
      typeof value.available !== 'boolean' || typeof value.pinned !== 'boolean' ||
      !text(value.state, 32) || !text(value.issue, 512)) return false;
  // Host paths are display text, not URLs: newlines and backslashes are valid
  // Unix filenames. Do not apply browser URL or Windows path rules here.
  return true;
}

function session(value: unknown): value is Session {
  return record(value) && typeof value.id === 'string' && sessionID.test(value.id) &&
    // Catalog SQL bounds name length to 4,096 Unicode characters, not the
    // live-sidebar's separate 256-byte presentation limit.
    text(value.name, 16_384) && [...value.name].length <= 4096 &&
    text(value.updated, 64) && typeof value.pinned === 'boolean' && typeof value.archived === 'boolean';
}

function unique<T extends { id: string }>(values: T[]): boolean {
  return new Set(values.map(value => value.id)).size === values.length;
}

// Accept only the exact local, canonical pagination routes generated by Go's
// url.Values.Encode. Never navigate to an arbitrary URL supplied in bootstrap.
export function catalogPageURL(value: string, id: string, current: number): string | null {
  if (!projectID.test(id) || !offset(current)) return null;
  const match = /^\/\?offset=(0|[1-9][0-9]{0,4})&project=([0-9a-f-]{36})&view=organization$/.exec(value);
  if (!match || match[2] !== id) return null;
  const next = Number(match[1]);
  return offset(next) && next > current
    ? `/?offset=${next}&project=${id}&view=organization` : null;
}

export function archivedPageURL(value: string): string | null {
  const match = /^\/\?archived_offset=([1-9][0-9]{0,4})&view=organization$/.exec(value);
  if (!match) return null;
  const next = Number(match[1]);
  return offset(next) ? `/?archived_offset=${next}&view=organization` : null;
}

/** Presentation validation only. The server remains the authority for every POST. */
function isOrganizationProps(value: unknown): value is OrganizationProps {
  if (!record(value) || typeof value.csrf !== 'string' || !/^[0-9a-f]{64}$/.test(value.csrf) || !text(value.error, 4096)) return false;
  const data = value.organization;
  if (data === null) return true;
  if (!record(data) || !Array.isArray(data.projects) || data.projects.length > 100 || !data.projects.every(project) ||
      !Array.isArray(data.archived) || data.archived.length > 25 || !data.archived.every(project) ||
      !unique([...data.projects, ...data.archived]) ||
      (data.project !== null && !project(data.project)) ||
      !Array.isArray(data.sessions) || data.sessions.length > 25 || !data.sessions.every(session) || !unique(data.sessions) ||
      !offset(data.offset) || typeof data.live !== 'boolean' || !text(data.nextURL, 256) || !text(data.archivedNextURL, 256)) return false;
  if (data.nextURL !== '' && (data.project === null || !catalogPageURL(data.nextURL, data.project.id, data.offset))) return false;
  if (data.archivedNextURL !== '' && !archivedPageURL(data.archivedNextURL)) return false;
  if ((data.project === null || data.live) && (data.sessions.length !== 0 || data.nextURL !== '')) return false;
  return true;
}

/** Return the checked projection, or fail before the React root is mounted. */
export function validateOrganizationProps(value: unknown): OrganizationProps {
  if (!isOrganizationProps(value)) throw new Error('Invalid organization page');
  return value;
}
