import {setTimeout as delay} from 'node:timers/promises';

export async function processChecks(h) {
  const {q,check,assert,wait,click,replace,snapshot,count,waitCount,release,posts,capture,idle,reload,evaluate,observations} = h;
  await replace('#live-prompt','Start one fictional managed worker in this isolated fixture project');
  await click('#live-send'); await waitCount(7); await release(7,'process');
  await wait(`!!${q('[data-permission="allow"]')}`, 'real Ask process_start approval');
  check((await snapshot()).permission?.tool==='process_start', 'Normal prompt reaches actual process_start Ask broker');
  await click('[data-session-menu]'); await click('[data-menu-key="processes"]');
  await wait(`${q('[data-process-status]')}.textContent==='0 managed processes'`, 'read inventory before approval');
  check(await count()===7, 'Inventory reads do not authorize process start');
  await click('[data-processes-close]');
  await click('[data-permission="allow"]'); await waitCount(8); await release(8,'fictional process started'); await idle();
  await click('[data-session-menu]'); await click('[data-menu-key="processes"]');
  await click('[data-process-refresh]');
  await wait(`!!${q('[data-process-logs]')}`, 'real running process inventory');
  const id = await evaluate(`${q('[data-process-logs]')}.dataset.processLogs`);
  check(/^proc_[a-f0-9]{32}$/.test(id), 'UI inventory exposes opaque current process handle, not PID');
  await click('[data-process-logs]');
  await wait(`${q('[data-process-output]')}.textContent.includes('FICTIONAL_MANAGER_PROCESS_READY')`, 'real bounded process output');
  await assert(`${q('[data-process-output]')}.children.length===0 && new TextEncoder().encode(${q('[data-process-output]')}.textContent).length<=32768`, 'Active process output is bounded plain text, never rendered HTML');
  await capture('process-running');
  await click('[data-process-stop]');
  await click('[data-process-stop-confirm]');
  await wait(`${q('[data-process-error]')}.textContent.includes('not acknowledged')`, 'Ask rejects direct Stop without fabricated approval');
  check(posts('stop').filter(p=>p.path.includes('/processes/')).length===1, 'Failed Stop is sent once with no automatic retry');
  await click('[data-process-refresh]');
  await wait(`${q('[data-process-list]')}.textContent.includes('running') && ${q('[data-process-stop]')}.disabled`, 'failed Stop latch retains process and disables blind retry');
  await click('[data-processes-close]');
  await click('[data-permission-policy-menu]'); await click('[data-menu-key="allow"]');
  await assert(`${q('[data-policy-confirm]')}.disabled`, 'Native session permission Allow requires explicit confirmation');
  await click('#workflow-permission-dialog input[type="checkbox"]'); await click('[data-policy-confirm]');
  await wait(`${q('[data-permission-policy-menu]')}.getAttribute('aria-label')==='Session permissions: Allow'`, 'native policy update acknowledged');
  check((await snapshot()).permission_mode==='allow', 'Real session permission changed to Allow through native UI');
  await reload(); await click('[data-session-menu]'); await click('[data-menu-key="processes"]');
  await wait(`!!${q('[data-process-stop]')} && !${q('[data-process-stop]')}.disabled`, 'reopened workspace current Stop authority');
  check(await evaluate(`${q('[data-process-stop]')}.dataset.processStop`)===id, 'Refreshed inventory still names exact current process');
  await click('[data-process-stop]');
  await click('[data-process-stop-confirm]');
  await wait(`${q('[data-process-list]')}.textContent.includes('stopped') || ${q('[data-process-list]')}.textContent.includes('exited')`, 'Allow Stop acknowledged and process reaped');
  check(posts('stop').filter(p=>p.path.includes('/processes/')).length===2 && posts('stop').filter(p=>p.path.includes('/processes/')).every(p=>p.process===id), 'Both explicit Stops target current opaque handle only');
  await click('[data-process-logs]');
  await wait(`${q('[data-process-log-status]')}.textContent.includes('end of output')`, 'stopped output EOF');
  await capture('process-stopped');
  await click('[data-processes-close]');
  const old = await snapshot();
  await click('[data-session-menu]'); await click('[data-menu-key="new"]'); await idle();
  await wait(`${q('#live-session')}.dataset.session!==${JSON.stringify(old.session_id)}`, 'native new conversation changes scope');
  await click('[data-session-menu]'); await click('[data-menu-key="processes"]');
  await wait(`${q('[data-process-status]')}.textContent==='0 managed processes'`, 'new session has no old process');
  const cleared = await evaluate(`({output:${q('[data-process-output]')}.textContent,hidden:${q('[data-process-log-panel]')}.hidden,list:${q('[data-process-list]')}.textContent,heading:${q('[data-process-log-heading]')}.textContent,cursor:${q('[data-process-log-status]')}.textContent,instance:${q('#managed-processes')}.dataset.processInstance,liveInstance:${q('#live-session')}.dataset.instance})`);
  observations.push({label:'new-session process scope',...cleared});
  await capture('process-new-scope');
  await assert(`${q('[data-process-output]')}.textContent==='' && ${q('[data-process-log-panel]')}.hidden && !${q('[data-process-list]')}.textContent.includes(${JSON.stringify(id)})`, 'Scope change clears old process output, handles and cursor view');
  await delay(250); check(await count()===8, 'Process inspection, Stop, policy change and scope change create no provider turns');
  await assert('document.documentElement.scrollWidth<=innerWidth+1', 'Production Goals/Processes workspace has no horizontal page overflow');
}
