//go:build ignore

// Reproduce Snow's pinned textarea component from the downloaded Bubbles module.
package main

import (
	"crypto/sha256"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
)

const destination = "internal/tui/textarea"
const header = "// Code generated by scripts/sync_textarea.go from Bubbles v2.2.1; DO NOT EDIT.\n// Copyright (c) 2020-2026 Charmbracelet, Inc. MIT license; see LICENSE and UPSTREAM.md.\n"

var check = flag.Bool("check", false, "verify generated files without writing")
var source = flag.String("source", "", "downloaded charm.land/bubbles/v2@v2.2.1 directory")

func main() {
	flag.Parse()
	if *source == "" {
		panic("-source is required")
	}
	for name, hash := range map[string]string{
		"textarea/textarea.go":                "825f72d9f4f703f4974fb8ffb81ba1ecac124f1abe69ee47c063a8b6cba06aaf",
		"textarea/selection.go":               "db4041a7578449f1f494914f65cba544f5667454101d06b89a7fc73b234d6b52",
		"internal/runeutil/runeutil.go":       "3d2abf109f37f5162cc7fd72c40d23d37cee6bfdb020089c3e63eef13057c116",
		"internal/memoization/memoization.go": "c6f0bac20dbd83e539df9d3de8b04ecdf63a6d2b9d157a78b17aa8ef2931172d",
	} {
		if got := fmt.Sprintf("%x", sha256.Sum256(read(name))); got != hash {
			panic("upstream source changed: " + name)
		}
	}
	input := string(read("textarea/textarea.go"))
	// Printable ASCII rune slices
	// have width len(slice). Keep upstream's Unicode path for everything else.
	for _, expression := range []string{"lines[row]", "word"} {
		input = strings.ReplaceAll(input, "uniseg.StringWidth(string("+expression+"))", "runeTextWidth("+expression+")")
	}
	input += `
func runeTextWidth(value []rune) int {
    for _, r := range value {
        if r < ' ' || r > '~' { return uniseg.StringWidth(string(value)) }
    }
    return len(value)
}
`
	input = strings.Replace(input, `len(m.Value()) == 0 && m.row == 0 && m.col == 0 && m.Placeholder != ""`, `m.row == 0 && m.col == 0 && m.Placeholder != "" && len(m.Value()) == 0`, 1)
	// Preserve every viewport row, but only style rows that it can display.
	// Update still prepares content before scrolling, and View renders again at
	// the resulting offset. Empty offscreen rows keep all scroll bounds intact.
	input = strings.Replace(input, "\tdisplayLine := 0", `
	// SetContent clamps an offset past the new bottom after edits/resizes.
	// Render the rows at that resulting offset, including its trailing empty row.
	visibleStart := min(m.viewport.YOffset(), max(0, m.totalVisualLines()+m.height+1-m.viewport.Height()))
	visibleEnd := visibleStart + m.viewport.Height()
	displayLine := 0`, 1)
	input = strings.Replace(input, "\t\tfor wl, wrappedLine := range wrappedLines {", `
		for wl, wrappedLine := range wrappedLines {
			if displayLine < visibleStart || displayLine >= visibleEnd {
				wrappedBase += len(wrappedLine)
				// Match upstream's trimmed trailing space in selection coordinates.
				if m.HasSelection() && len(wrappedLine) > 0 && wrappedLine[len(wrappedLine)-1] == ' ' && runeTextWidth(wrappedLine) > m.width {
					wrappedBase--
				}
				s.WriteByte('\n')
				displayLine++
				continue
			}`, 1)
	input = strings.Replace(input, "\tfor range m.height {\n\t\ts.WriteString(m.promptView(displayLine))", `
	for range m.height {
		if displayLine < visibleStart || displayLine >= visibleEnd {
			s.WriteByte('\n')
			displayLine++
			continue
		}
		s.WriteString(m.promptView(displayLine))`, 1)
	splitSource(input, false)
	splitSource(string(read("textarea/textarea_test.go")), true)
	for _, name := range []string{"textarea/selection.go", "textarea/selection_test.go", "internal/runeutil/runeutil.go", "internal/runeutil/runeutil_test.go", "internal/memoization/memoization.go", "internal/memoization/memoization_test.go"} {
		relative := strings.TrimPrefix(name, "textarea/")
		write(relative, []byte(header+string(read(name))))
	}
	write("LICENSE", read("LICENSE"))
}

func read(name string) []byte {
	data, err := os.ReadFile(filepath.Join(*source, name))
	if err != nil {
		panic(err)
	}
	return data
}

func write(name string, data []byte) {
	path := filepath.Join(destination, name)
	if strings.HasSuffix(name, ".go") {
		data = []byte(strings.ReplaceAll(string(data), "charm.land/bubbles/v2/internal/", "github.com/elmissouri16/snow-core/internal/tui/textarea/internal/"))
		var err error
		data, err = format.Source(data)
		if err != nil {
			panic(fmt.Errorf("%s: %w", name, err))
		}
		if strings.Count(string(data), "\n") > 1000 {
			panic("file exceeds 1,000 lines: " + name)
		}
	}
	if *check {
		current, err := os.ReadFile(path)
		if err != nil || string(current) != string(data) {
			panic("generated file differs: " + path)
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(path, data, 0644); err != nil {
		panic(err)
	}
}

func group(name string, test bool) string {
	if test {
		switch {
		case strings.Contains(name, "DynamicHeight"), strings.Contains(name, "MaxContentHeight"):
			return "height_test"
		case strings.Contains(name, "Selection"), name == "TestSelectAll":
			return "editing_selection_test"
		case strings.HasPrefix(name, "Test"):
			return "editing_test"
		default:
			return "helpers_test"
		}
	}
	switch name {
	case "Update":
		return "update"
	case "StyleState", "Styles", "CursorStyle", "DefaultStyles", "DefaultLightStyles", "DefaultDarkStyles", "SetStyles", "activeStyle", "VirtualCursor", "SetVirtualCursor", "updateVirtualCursorStyle":
		return "styles"
	case "view", "View", "promptView", "lineNumberView", "placeholderView", "Blink", "Cursor":
		return "view"
	case "deleteSelection", "DeleteSelection", "CopySelection", "startKeyboardSelection", "updateKeyboardSelection":
		return "editing_selection"
	case "memoizedWrap", "wrap", "repeatSpaces", "runeTextWidth", "SetWidth", "Width", "SetHeight", "Height", "SetPromptFunc", "totalVisualLines", "recalculateHeight", "atContentLimit", "visualLinesForInsert", "numDigits", "clamp", "abs":
		return "layout"
	case "setCursorLineRelative", "CursorDown", "CursorUp", "SetCursorColumn", "CursorStart", "CursorEnd", "characterRight", "characterLeft", "wordLeft", "wordRight", "doWordRight", "LineInfo", "repositionView", "MoveToBegin", "MoveToEnd", "PageUp", "PageDown", "cursorLineNumber":
		return "navigation"
	case "New", "DefaultKeyMap", "Hash":
		return "model"
	}
	if strings.HasPrefix(name, "computed") {
		return "styles"
	}
	if name == "" || name == "KeyMap" || name == "PromptInfo" || name == "line" || name == "Model" {
		return "model"
	}
	return "editing"
}

func splitSource(input string, test bool) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "source.go", input, parser.ParseComments)
	if err != nil {
		panic(err)
	}
	pieces := map[string][]string{}
	for _, decl := range file.Decls {
		start := decl.Pos()
		name := ""
		switch decl := decl.(type) {
		case *ast.GenDecl:
			if decl.Tok == token.IMPORT {
				continue
			}
			if decl.Doc != nil {
				start = decl.Doc.Pos()
			}
			if spec, ok := decl.Specs[0].(*ast.TypeSpec); ok {
				name = spec.Name.Name
			}
		case *ast.FuncDecl:
			name = decl.Name.Name
			if decl.Doc != nil {
				start = decl.Doc.Pos()
			}
			if name == "TestView" {
				splitViewTest(input, fset, decl, pieces)
				continue
			}
		}
		key := group(name, test)
		pieces[key] = append(pieces[key], input[fset.Position(start).Offset:fset.Position(decl.End()).Offset])
	}
	for key, parts := range pieces {
		body := strings.Join(parts, "\n\n")
		renderFile(key+".go", body, file.Imports)
	}
}

func renderFile(name, body string, imports []*ast.ImportSpec) {
	parsed, err := parser.ParseFile(token.NewFileSet(), "body.go", "package textarea\n"+body, 0)
	if err != nil {
		panic(err)
	}
	used := map[string]bool{}
	ast.Inspect(parsed, func(node ast.Node) bool {
		if selector, ok := node.(*ast.SelectorExpr); ok {
			if ident, ok := selector.X.(*ast.Ident); ok {
				used[ident.Name] = true
			}
		}
		return true
	})
	var lines []string
	for _, spec := range imports {
		path, _ := strconv.Unquote(spec.Path.Value)
		name := filepath.Base(path)
		prefix := ""
		if strings.HasSuffix(path, "/v2") {
			name = filepath.Base(filepath.Dir(path))
		}
		if spec.Name != nil {
			name, prefix = spec.Name.Name, spec.Name.Name+" "
		}
		if used[name] {
			lines = append(lines, prefix+spec.Path.Value)
		}
	}
	slices.Sort(lines)
	text := header + "package textarea\n"
	if len(lines) > 0 {
		text += "import (\n" + strings.Join(lines, "\n") + "\n)\n"
	}
	write(name, []byte(text+body+"\n"))
}

// Split upstream's large view fixture table by feature, preserving every case.
func splitViewTest(input string, fset *token.FileSet, fn *ast.FuncDecl, pieces map[string][]string) {
	var table *ast.CompositeLit
	for _, stmt := range fn.Body.List {
		if assign, ok := stmt.(*ast.AssignStmt); ok && len(assign.Rhs) == 1 {
			if lit, ok := assign.Rhs[0].(*ast.CompositeLit); ok {
				table = lit
				break
			}
		}
	}
	if table == nil {
		panic("upstream TestView fixture table changed")
	}
	groups := map[string][]string{}
	for _, element := range table.Elts {
		literal := element.(*ast.CompositeLit)
		name := literal.Elts[0].(*ast.KeyValueExpr).Value.(*ast.BasicLit).Value
		category := "Content"
		switch {
		case strings.Contains(name, "width"):
			category = "Width"
		case strings.Contains(name, "height"):
			category = "Height"
		case strings.Contains(name, "cursor"), strings.Contains(name, "page"), strings.Contains(name, "move"), strings.Contains(name, "scroll"):
			category = "Navigation"
		case strings.Contains(name, "prompt"), strings.Contains(name, "buffer"), strings.Contains(name, "line numbers"):
			category = "Chrome"
		}
		groups[category] = append(groups[category], input[fset.Position(element.Pos()).Offset:fset.Position(element.End()).Offset])
	}
	pieces["view_helpers_test"] = []string{`type want struct { view string; cursorRow, cursorCol int }
type viewTestCase struct { name string; modelFunc func(Model) Model; want want }`}
	last := fn.Body.List[len(fn.Body.List)-1]
	loop := input[fset.Position(last.Pos()).Offset:fset.Position(last.End()).Offset]
	pieces["view_helpers_test"] = append(pieces["view_helpers_test"], "func runViewCases(t *testing.T, tests []viewTestCase) {\n"+loop+"\n}")
	for category, cases := range groups {
		pieces["view_"+strings.ToLower(category)+"_test"] = []string{"func TestView" + category + "(t *testing.T) { t.Parallel(); runViewCases(t, []viewTestCase{\n" + strings.Join(cases, ",\n") + ",\n})\n}"}
	}
}
