// Native production React grouped inventory contract. Real lifecycle/facades,
// deferred read-only transport; browser.mjs separately owns production geometry.
import {component} from './component.mjs';
await component(async ({evaluate,check,click,settle,ids})=>{
  const toggle=i=>`[data-sidebar-project="${ids[i]}"] [data-workspace-toggle]`;
  await check('calls.length===1 && calls[0].url.includes(ids[0])','Only selected branch reads initial inventory');
  await evaluate(`reply(0,[{session_id:'a1',name:'First'}]);`);await settle();
  await check('row("a1").querySelector("a").getAttribute("aria-current")==="page"','Cold selected row is selected');
  await click(toggle(1));
  await evaluate(`reply(1,[{session_id:'b1',name:'Second'}],'worker-b');`);await settle();
  await check('document.querySelectorAll("[data-workspace-toggle][aria-expanded=true]").length===2','Independent disclosures remain open');
  await check('row("b1").querySelector("a").dataset.instance==="worker-b"','Validated live inventory stamps exact instance');
  await evaluate(`window.oldRow=row('b1');window.oldLink=oldRow.querySelector('a');oldLink.focus();window.changes=[];window.observer=new MutationObserver(records=>changes.push(...records));observer.observe(group(1),{childList:true,subtree:true,attributes:true,characterData:true});SnowSidebarSessions.syncVisibility(false);`);await settle();
  await check('changes.length===0 && document.activeElement===oldLink && calls.length===2','No-op visibility mutates no DOM, steals no focus, reads nothing');
  await evaluate('observer.disconnect()');await click(toggle(1));await click(toggle(1));
  await check('calls.length===2 && row("b1")===oldRow','Loaded branch collapse/reopen reuses keyed row without redundant reads');
  await evaluate(`SnowSidebarSessions.invalidate(ids[1]);reply(2,[{session_id:'b1',name:'Second'}],'worker-b');`);await settle();
  await check('calls.length===3 && row("b1")===oldRow','Explicit invalidation refresh preserves unchanged keyed row');
  await evaluate('swap()');await settle();
  await check('document.querySelectorAll("[data-workspace-toggle][aria-expanded=true]").length===2 && row("b1")!==null && calls.length===5','Real root unmount/remount retains expanded cached rows and revalidates exactly two expanded inventories');
  await check('row("b1")!==oldRow && !oldRow.isConnected','Real ancestor replacement retires old React-owned nodes');
  await evaluate(`reply(3,[{session_id:'a1',name:'First'}]);reply(4,[{session_id:'b1',name:'Second'}],'worker-b');`);await settle();
  await click(toggle(2));await click(toggle(2));await click(toggle(2));
  await check('calls.length===6','Repeated expansion during pending read does not duplicate request');
  await evaluate(`SnowSidebarSessions.invalidate(ids[2]);reply(6,[{session_id:'new',name:'New'}]);reply(5,[{session_id:'stale',name:'Stale'}]);`);await settle();
  await check('pending[5].options.signal.aborted && row("new")!==null && !row("stale")','Explicit superseding invalidation aborts old read; late old response cannot overwrite newer inventory');
  await evaluate(`SnowSidebarSessions.invalidate(ids[1]);window.detachedRequest=pending.length-1;swap();`);await settle();
  await check('pending[detachedRequest].options.signal.aborted && calls.length===11','Ancestor cleanup aborts detached pending request; remount reads only three expanded inventories');
  await evaluate(`reply(detachedRequest,[{session_id:'detached',name:'Detached'}],'stale-worker');reply(8,[{session_id:'a1',name:'First'}]);reply(9,[{session_id:'b1',name:'Second'}],'worker-b');reply(10,[{session_id:'new',name:'New'}]);`);await settle();
  await check('!row("detached") && row("b1").querySelector("a").dataset.instance==="worker-b"','Detached generation cannot change cached rows or owner metadata');
  await evaluate(`SnowSidebarSessions.invalidate(ids[2]);reply(11,Array.from({length:100},(_,i)=>({session_id:'bounded'+i,name:'Row '+i})), '', {has_more:true,next_offset:100,truncated:true});`);await settle();
  await check('group(2).querySelectorAll("[data-shell-session]").length===100 && group(2).querySelector("[data-sidebar-session-more]").hidden','Inventory bound caps 100 rows and hides further paging');
  await evaluate('SnowSidebarSessions.syncVisibility(true)');await settle();
  await check('[...document.querySelectorAll("[data-workspace-sessions]")].every(x=>x.hidden) && calls.length===12','Hiding inventory keeps disclosure/cache state without fetching');
  await evaluate('SnowSidebarSessions.syncVisibility(false)');await settle();
  await check('[...document.querySelectorAll("[data-workspace-sessions]")].every(x=>!x.hidden) && calls.length===12','Showing loaded branches does not fan out reads');
  await evaluate(`SnowSidebarSessions.invalidate(ids[1]);reply(12,[{session_id:'wrong-scope',name:'Wrong'}],'worker-b',{project_id:ids[0]});`);await settle();
  await check('!row("wrong-scope") && row("b1")!==null && group(1).querySelector("[data-sidebar-session-status]").textContent.includes("could not be loaded")','Wrong-project response fails closed without replacing valid cached rows');
  await settle();
  await check('calls.length===13 && !group(1).querySelector("[data-sidebar-session-more]").hidden','Failed inventory is not replayed; explicit Retry remains available');
  await click(`[data-sidebar-project="${ids[1]}"] [data-sidebar-session-more]`);
  await evaluate(`reply(13,[{session_id:'b1',name:'<img src=x onerror=alert(1)>'}],'worker-b');`);await settle();
  await check('calls.length===14 && row("b1").textContent.includes("<img src=x onerror=alert(1)>") && !row("b1").querySelector("img")','Only explicit Retry reads again; untrusted names remain text, never markup');
  await evaluate(`SnowSidebarSessions.invalidate(ids[2]);reply(14,Array.from({length:101},(_,i)=>({session_id:'overflow'+i,name:'Overflow'})));`);await settle();
  await check('group(2).querySelectorAll("[data-shell-session]").length===100 && !row("overflow0") && calls.length===15','Oversized inventory fails closed and preserves bounded prior rows');
  await evaluate(`SnowSidebarSessions.invalidate(ids[0]);window.preempted=pending.length-1;SnowShell.preemptInventory();reply(preempted,[{session_id:'late',name:'Late'}]);`);await settle();
  await check('pending[preempted].options.signal.aborted && !row("late") && calls.length===16','Explicit activation preemption aborts pending inventory without retry or stale adoption');
  await check('intents.length===0 && navigation.length===0 && inspections.length===0 && browserReads===3','Inventory lifecycle emits no activation/session/presentation intents; one browser inventory per mount');
});
