/* Source-asset fixture: no manager, provider, or filesystem activation. */
window.runInspectionPolish = async ({assert, tick, requests, pending}) => {
  const $ = selector => document.querySelector(selector);
  const panel = $("#project-inspector");
  const list = (path, entries = [], extra = {}) => ({path, entries, has_more: false, next_offset: 0, ...extra});
  const entry = (name, kind = "file", path = name) => ({name, kind, path});
  const reply = async (kind, data) => { pending(kind).at(-1).resolve(data); await tick(); };
  const key = (node, key) => node.dispatchEvent(new KeyboardEvent("keydown", {key, bubbles: true}));
  const content = "diff --git a/demo.txt b/demo.txt\n--- a/demo.txt\n+++ b/demo.txt\n@@ -1 +1 @@\n-<script>bad()</script>\n+<img src=x onerror=bad()>\n context\n";
  const fileTab = $("#inspection-tab-files");
  fileTab.click();
  await reply("files", list(".", [entry("an-extremely-long-filename-that-should-preserve-extension.ts"), entry("file10.txt"), entry("directory", "directory"), entry("file2.txt")]));
  assert([...panel.querySelectorAll("[data-inspection-entry]")].map(b => b.dataset.inspectionEntry).join("/") === "directory/an-extremely-long-filename-that-should-preserve-extension.ts/file2.txt/file10.txt", "files are naturally ordered with directories first independently of paging");
  assert($("[data-files-list] .inspection-extension").textContent === ".ts", "file extension has a nonshrinking name seat");
  assert($("[data-files-list] .inspection-icon")?.getAttribute("aria-hidden") === "true", "file and folder icons are decorative local SVG");
  assert($("[data-inspection-up]").disabled && $("[data-inspection-crumb]").getAttribute("aria-current") === "location", "root navigation is current and parent disabled");
  const row = $("[data-entry-kind=file]"); row.click();
  assert(row.getAttribute("aria-busy") === "true" && !row.hasAttribute("aria-current"), "loading file has busy row without a false completed selection");
  const first = pending("file").at(-1);
  $("#inspection-tab-project").click();
  first.resolve({path: "stale.ts", text: "STALE"}); await tick(); fileTab.click();
  assert(first.options.signal.aborted && $("[data-file-preview]").hidden, "tab leave aborts file and prevents late preview");
  row.click(); await reply("file", {path: row.dataset.inspectionEntry, text: "<script>bad()</script>\n  literal UTF-8 λ", truncated: false});
  assert($("[data-file-content]").textContent.includes("<script>") && !$("[data-file-content] script"), "file preview remains literal UTF-8 not interpreted markup");
  assert(row.getAttribute("aria-current") === "true" && !row.hasAttribute("aria-busy"), "successful file clears busy and marks selection");
  row.click(); await reply("file", {path: "empty.txt", text: ""});
  assert(!$("[data-file-preview]").hidden && $("[data-file-notice]").textContent === "This file is empty.", "empty file has explicit read-only state");
  row.click(); await reply("file", {path: "large.txt", text: "a".repeat(65550)});
  assert($("[data-file-content]").textContent.length === 65536 && $("[data-file-notice]").textContent.includes("truncated"), "file preview bounds and truncation notice agree");
  row.click(); const stale = pending("file").at(-1);
  $("[data-inspection-refresh=files]").click();
  const n = pending("file").length;
  row.dispatchEvent(new MouseEvent("click", {bubbles: true}));
  assert(row.disabled && !row.hasAttribute("aria-current") && pending("file").length === n, "file refresh disables stale rows and clears selection");
  stale.resolve({path: "stale.txt", text: "STALE"}); await tick();
  assert($("[data-file-preview]").hidden, "late file cannot publish during list refresh");
  await reply("files", list(".", [entry("folder", "directory")]));
  $("[data-entry-kind=directory]").click();
  await reply("files", list("folder/deep", [entry("one.txt", "file", "folder/deep/one.txt")], {has_more: true, next_offset: 1}));
  assert([...panel.querySelectorAll("[data-inspection-crumb]")].map(b => b.textContent).join("/") === "Project root/folder/deep", "breadcrumbs expose root and every ancestor");
  $("[data-files-more]").click();
  assert(new URLSearchParams(pending("files").at(-1).options.body).get("offset") === "1" && $("[data-files-more]").disabled, "paging sends authoritative offset and disables while pending");
  await reply("files", list("folder/deep", [entry("two.txt", "file", "folder/deep/two.txt")]));
  assert(panel.querySelectorAll("[data-inspection-entry]").length === 2 && $("[data-files-more]").hidden, "paging appends rows and hides exhausted page control");
  $("[data-inspection-crumb='folder']").click();
  assert(new URLSearchParams(pending("files").at(-1).options.body).get("path") === "folder", "breadcrumb navigates through existing bounded files route");
  await reply("files", list("folder"));
  assert($("[data-files-status]").textContent.includes("No visible files"), "empty folder describes omitted protected entries");
  $("[data-inspection-refresh=files]").click(); await reply("files", list("folder", [entry("kept.txt")]));
  $("[data-inspection-refresh=files]").click(); await reply("files", {path: "folder", entries: null});
  assert(!$("[data-files-error]").hidden && $("[data-files-error]").textContent.includes("stale") && $("[data-inspection-entry]").disabled, "failed file refresh labels stale rows and keeps them inert");
  $("[data-inspection-refresh=files]").click(); await reply("files", list("folder", [entry("recovered.txt")]));
  assert($("[data-files-error]").hidden && !$("[data-inspection-entry]").disabled, "successful file retry removes error and restores rows");
  key(fileTab, "ArrowRight");
  assert(document.activeElement === $("#inspection-tab-changes") && fileTab.tabIndex === -1, "tabs implement roving keyboard focus");
  $("[data-inspection-refresh=changes]").click();
  await reply("changes", {available: true, changes: [{path: "demo.txt", kind: "unstaged", status: "Modified"}]});
  $("[data-inspection-change]").click(); await reply("diff", {available: true, path: "demo.txt", text: content});
  assert($("[data-diff-content]").textContent === content, "diff presentation preserves original text exactly");
  assert($(".inspection-diff-added")?.textContent.startsWith("+") && $(".inspection-diff-removed")?.textContent.startsWith("-"), "diff additions and deletions have semantic color classes and literal signs");
  assert($(".inspection-diff-hunk")?.textContent.startsWith("@@") && panel.querySelectorAll(".inspection-diff-meta").length === 3, "diff metadata is distinguished from additions");
  assert(!$("[data-diff-content] img") && !$("[data-diff-content] script"), "diff markup cannot create active host content");
  assert($(".inspection-diff-added").getBoundingClientRect().height === 20, "unified diff rows keep one consistent 20px line height");
  $("[data-inspection-change]").click();
  const manyLines = "+\n".repeat(5000);
  await reply("diff", {available: true, path: "many-lines.diff", text: manyLines});
  assert($("[data-diff-content]").textContent === manyLines && $("[data-diff-content]").children.length <= 4097, "diff line decoration is bounded without discarding text");

  $("[data-inspection-refresh=changes]").click(); await reply("changes", {available: false, changes: [], reason: "Not a Git repository"});
  assert($("[data-changes-status]").textContent === "Not a Git repository" && !$("[data-inspection-change]"), "non-Git project has explicit unavailable state without fake diff");
  $("[data-inspection-refresh=changes]").click(); await reply("changes", {available: true, changes: []});
  assert($("[data-changes-status]").textContent === "No working changes reported.", "clean Git state is distinct from unavailable");
  key($("#inspection-tab-changes"), "End");
  assert(document.activeElement === $("#inspection-tab-project") && !$("#inspection-project").hidden, "End selects Project without inspection network calls");
  assert(!panel.querySelector("select") && !panel.querySelector("[contenteditable=true]"), "inspector has no native select or fake editor controls");
  $(".remove-project").open = true;
  assert($(".remove-project input").required && $(".remove-project").textContent.includes("keep all files"), "project removal retains explicit confirmation and retention boundary");

  const region = $(".tool-timeline");
  const snapshot = activities => ({activities});
  SnowVisibility.renderActivities(region, snapshot([{id: "one", tool: "read", status: "running", summary: "public/file.txt"}]));
  const activity = $(".tool-activity"); activity.open = true;
  SnowVisibility.renderActivities(region, snapshot([{id: "one", tool: "read", status: "completed", summary: "public/file.txt", output: "<img src=x>\npublic output"}]));
  assert($(".tool-activity") === activity && activity.open, "public activity disclosure survives polling completion");
  assert($(".activity-output").textContent.includes("<img") && !$(".activity-output img"), "public activity output stays inert text");
  SnowVisibility.renderActivities(region, snapshot([{id: "one", tool: "read", status: "failed", summary: "public error", output: "bounded error"}]));
  assert(activity.classList.contains("activity-error") && $(".activity-status").textContent === "Failed", "public failure has visible label as well as color");
  SnowVisibility.renderActivities(region, snapshot([{id: "one", tool: "read", status: "completed"}]));
  assert(!activity.open && $(".tool-activity summary").getAttribute("aria-disabled") === "true", "completed no-output activity is not a fake disclosure");
  SnowVisibility.renderActivities(region, snapshot([{id: "one", tool: "read", status: "completed", output: "x".repeat(17000), truncated: true}]));
  assert($(".activity-output").textContent.length === 16384 && !$(".activity-truncated").hidden, "public tool output bound is disclosed");
  SnowVisibility.renderActivities(region, snapshot([]));
  assert(region.hidden && !$(".tool-activity"), "empty public activity timeline does not leave obsolete rows");

  // These run at desktop, 320x240 overlay, and 768x360 stacked viewport.
  await tick();
  const rect = panel.getBoundingClientRect();
  assert(rect.left >= -1 && rect.right <= innerWidth + 1 && rect.top >= -1 && rect.bottom <= innerHeight + 1, "inspector bounds stay inside current viewport");
  const active = $("#inspection-project");
  assert(getComputedStyle(active).overflowY === "auto" && active.clientHeight > 0 && getComputedStyle(panel).overflowY === "hidden", "panel has one reachable vertical content scroller");
  const remove = $(".remove-project button"); remove.scrollIntoView({block: "nearest"});
  const actionRect = remove.getBoundingClientRect(), activeRect = active.getBoundingClientRect();
  assert(actionRect.top >= activeRect.top - 1 && actionRect.bottom <= activeRect.bottom + 1, "last Project action is reachable by panel scroll at short height");
  assert($("[data-inspector-toggle]").getBoundingClientRect().bottom <= innerHeight && $(".inspector-tabs").getBoundingClientRect().bottom <= innerHeight, "close and all tabs remain outside content scroll and visible");
  assert(document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight, "inspector composition does not overflow the document");
  assert(!requests.some(r => /activate|prompt|permission|command/.test(r.url)), "all inspection interactions remain read-only public endpoint requests");
  fileTab.click(); $("[data-inspection-entry]").click();
  const replacedRequest = pending("file").at(-1);
  const replacement = panel.cloneNode(true); replacement.dataset.project = "different-project";
  panel.replaceWith(replacement); SnowInspection.init(); SnowInspection.opened();
  replacedRequest.resolve({path: "previous-session.txt", text: "OLD SESSION"}); await tick();
  assert(replacedRequest.options.signal.aborted && $("[data-file-preview]").hidden, "replaced inspector rejects previous instance file response");
  await reply("files", list(".", [entry("new-project.txt")]));
  $("[data-inspection-entry]").click(); await reply("file", {path: "new-project.txt", text: "NEW PROJECT"});
  assert($("[data-file-content]").textContent === "NEW PROJECT" && pending("file").at(-1).url.includes("different-project"), "replacement inspector uses its own project authority");
  const beforeUnavailable = requests.length;
  replacement.dataset.available = "false";
  $("#inspection-tab-changes").click(); $("[data-inspection-refresh=changes]").click();
  assert(requests.length === beforeUnavailable && !$("[data-changes-error]").hidden, "unavailable project reports identity error without inspection requests");
};
